ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.eshop.bff.ApplicationKt.module ]
    }
}

jwt {
    audience = ""
    issuer = "https://login.microsoftonline.com/{tenant-id}/v2.0"
    realm = "eshop-bff"
}

cors {
    allowedOrigins = ["http://localhost:3000"]
}
